language: python

python:
  - "2.7"
  - "3.6"

env:
  - INSTALL_TYPE="standard"
  - INSTALL_TYPE="dev"
  - INSTALL_TYPE="minimal"

install:
  - |
    # Python setup
    set -e

    echo -e "\n *** Inspecting travis base environment"
    pip freeze
    # Work-around for: https://github.com/pandas-dev/pandas/issues/25316
    pip uninstall -y -q numpy

    echo -e "\n *** Updating pip + setuptools"
    pip install -U pip setuptools
    pip config list

    cd src_backend_python
    echo -e "\n *** Installing tabloo"
    if [[ $INSTALL_TYPE = "standard" ]]; then
      #  For now neither of the following works:
      #  - python setup.py install
      #  - pip install .
      # The latter seems to be caused by README.md being a symlink, great pip...
      rm -rf ./dist
      python setup.py bdist_wheel
      pip install ./dist/*.whl
    elif [[ $INSTALL_TYPE = "dev" ]]; then
      pip install -I -e .
    elif [[ $INSTALL_TYPE = "minimal" ]]; then
      pip install -I -e .
      pip install flask==1.0.0 flask-cors==3.0.0 pandas==0.19.2
    fi

    echo -e "\n *** Installing test dependencies"
    pip install -U pytest pytest-cov

    echo -e "\n *** Installed packages:"
    pip freeze

    echo -e "\n *** Installing node packages:"
    cd $TRAVIS_BUILD_DIR
    npm install

script:
  - cd $TRAVIS_BUILD_DIR
  - npm run check-types
  - pwd && ls -lh
  - pwd && cd src_backend_python && py.test && cd $TRAVIS_BUILD_DIR
  - pwd && tabloo_cli -h
