filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.nim"
      - "*.scss"
      - "*.html"
      - "nim.cfg"
      - "*.js"
      - "*.ts"
    exclude:
      - "dist/main.js"
    match_mode: "fnmatch"
    exclude_gitignore: true

tasks:
  default:
    fileset: default
    commands:
      - "npx webpack"

default_task: default
log: true
sound: false
notifications: true
