filesets:
  default:
    include:
      - ".watchcode.yaml"
      - "*.nim"
      - "*.scss"
      - "*.html"
      - "nim.cfg"
    exclude:
    match_mode: "fnmatch"
    exclude_gitignore: true

tasks:
  default:
    fileset: default
    commands:
      #- "npm start"
      #- "nim js -o:./build/main.js ./src_frontend/main.nim"
      - "nim js -d:debugOOP -o:./build/main.js ./src_frontend/dev/test_table.nim"

default_task: default
log: false
sound: true
notifications: true
